In [1]:
import time
from rich.console import Console
import ipywidgets as widgets


def do_something_important():
    time.sleep(5.0)  # Simulates a long process

console = Console()
with console.status(
    "Please wait - solving global problems...", spinner="earth"
):
    do_something_important()

console.print("All fixed! :sunglasses:")

Output()

All fixed! 😎

In [2]:
console.print("[yellow]Hi[/yellow] [green underline]World")

Hi World

In [3]:
from termcolor import colored

text = colored("Hello, World!", "red")
print(text)

Hello, World!

In [4]:
import ipywidgets as widgets

from ipywidgets import IntSlider
import IPython.display as display

slider = IntSlider(value=5, min=0, max=10)
display.display(slider)

IntSlider(value=5, max=10)

In [5]:
import pandas as pd
import yfinance as yf
idk = yf.download(tickers="AAPL", interval="15m", start="2026-03-31", end="2026-04-01")

[*********************100%***********************]  1 of 1 completed

In [6]:
aapl_values = []
for i in idk.iloc[:, 0:1]:
    for j in idk[i]:
        aapl_values.append(j)
print(aapl_values)
#min_val = min(aapl_values)
#max_val = max(aapl_values)

[247.82000732421875, 248.81500244140625, 248.50999450683594, 248.94009399414062, 247.61000061035156, 247.32000732421875, 248.3800048828125, 248.42999267578125, 248.63499450683594, 248.61000061035156, 249.46499633789062, 250.33999633789062, 251.77000427246094, 253.1300048828125, 253.25, 253.22500610351562, 252.58009338378906, 252.5399932861328, 252.8000030517578, 253.1300048828125, 253.39999389648438, 253.7550048828125, 253.89500427246094, 253.6699981689453, 253.9499969482422, 253.7899932861328]

In [7]:
scaled_aapl = []
for i in aapl_values:
    min_val = min(aapl_values)
    max_val = max(aapl_values)
    scale = i - min_val
    range_ = max_val - min_val
    pos_ = scale/range_
    map_ = pos_ * 19
    new_y = round(19 - map_)
    scaled_aapl.append(new_y)
print(scaled_aapl)
len(scaled_aapl)

[18, 15, 16, 14, 18, 19, 16, 16, 15, 15, 13, 10, 6, 2, 2, 2, 4, 4, 3, 2, 2, 1, 0, 1, 0, 0]

26

In [8]:
idk.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 26 entries, 2026-03-31 13:30:00+00:00 to 2026-03-31 19:45:00+00:00
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   26 non-null     float64
 1   (High, AAPL)    26 non-null     float64
 2   (Low, AAPL)     26 non-null     float64
 3   (Open, AAPL)    26 non-null     float64
 4   (Volume, AAPL)  26 non-null     int64
dtypes: float64(4), int64(1)
memory usage: 1.2 KB

In [9]:
idk.iloc[:, 0:1]

Price                           Close
Ticker                           AAPL
Datetime
2026-03-31 13:30:00+00:00  247.820007
2026-03-31 13:45:00+00:00  248.815002
2026-03-31 14:00:00+00:00  248.509995
2026-03-31 14:15:00+00:00  248.940094
2026-03-31 14:30:00+00:00  247.610001
2026-03-31 14:45:00+00:00  247.320007
2026-03-31 15:00:00+00:00  248.380005
2026-03-31 15:15:00+00:00  248.429993
2026-03-31 15:30:00+00:00  248.634995
2026-03-31 15:45:00+00:00  248.610001
2026-03-31 16:00:00+00:00  249.464996
2026-03-31 16:15:00+00:00  250.339996
2026-03-31 16:30:00+00:00  251.770004
2026-03-31 16:45:00+00:00  253.130005
2026-03-31 17:00:00+00:00  253.250000
2026-03-31 17:15:00+00:00  253.225006
2026-03-31 17:30:00+00:00  252.580093
2026-03-31 17:45:00+00:00  252.539993
2026-03-31 18:00:00+00:00  252.800003
2026-03-31 18:15:00+00:00  253.130005
2026-03-31 18:30:00+00:00  253.399994
2026-03-31 18:45:00+00:00  253.755005
2026-03-31 19:00:00+00:00  253.895004
2026-03-31 19:15:00+00:00  253.669998
2026-03-31 19:30:00+00:00  253.949997
2026-03-31 19:45:00+00:00  253.789993

In [10]:
idklol = yf.download(tickers="MSFT", interval="15m", period="1d")
idklol

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT
Datetime,,,,,
2026-04-01 13:30:00+00:00,369.334015,373.989990,369.049988,373.160004,4198881
2026-04-01 13:45:00+00:00,369.630005,370.309998,368.200012,369.390015,1666939
2026-04-01 14:00:00+00:00,371.174988,371.390015,369.450012,369.595001,1171229
2026-04-01 14:15:00+00:00,371.510010,372.089996,371.059998,371.170013,988446
2026-04-01 14:30:00+00:00,371.350006,372.049011,370.170013,371.529999,1037230
2026-04-01 14:45:00+00:00,371.800690,372.200012,371.081909,371.320007,788310
2026-04-01 15:00:00+00:00,371.904999,372.500000,371.350098,371.779999,879140
2026-04-01 15:15:00+00:00,371.234985,372.149994,371.000000,371.940002,716474
2026-04-01 15:30:00+00:00,372.125000,372.299896,370.750000,371.239990,615176
2026-04-01 15:45:00+00:00,372.184998,372.470001,372.000000,372.130005,557492
2026-04-01 16:00:00+00:00,372.109985,372.619995,372.070007,372.170013,558872
2026-04-01 16:15:00+00:00,372.609985,372.839996,371.959991,372.095001,470085
2026-04-01 16:30:00+00:00,372.720001,372.809998,372.010010,372.640015,464843
2026-04-01 16:45:00+00:00,372.522003,372.880005,372.100006,372.720001,529982
2026-04-01 17:00:00+00:00,372.464996,372.829987,372.244995,372.529999,507112
2026-04-01 17:15:00+00:00,371.890015,372.630005,371.880005,372.480011,452057
2026-04-01 17:30:00+00:00,371.285004,372.019989,371.110107,371.906189,572672
2026-04-01 17:45:00+00:00,370.785614,371.500000,370.700012,371.269989,439297
2026-04-01 18:00:00+00:00,370.369995,370.880005,370.100006,370.750000,599007
2026-04-01 18:15:00+00:00,369.059998,370.380005,368.940002,370.359985,872986
2026-04-01 18:30:00+00:00,369.359985,369.700012,368.725006,369.075012,630983
2026-04-01 18:45:00+00:00,369.290009,369.600006,368.875000,369.359985,518374
2026-04-01 19:00:00+00:00,368.915009,369.693604,368.899994,369.290009,580874
2026-04-01 19:15:00+00:00,369.285004,369.910004,368.869995,368.904999,884949
2026-04-01 19:30:00+00:00,369.190002,369.769989,368.869995,369.285004,858345
2026-04-01 19:45:00+00:00,369.450012,369.749512,368.880005,369.190002,1935228

In [15]:
for k in range(16,10-1,-1):
    print(k)

16
15
14
13
12
11
10